### PR TITLE
fixed the bug (coins should be an arraylist of Coin).

### LINKED ISSUE #92: Coins under an array list of Hearts?
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Background.java#L13

If the coins are of heart type, you may want to either rename it to something more generic or have coins have their own class

### PR DESCRIPTION
**Pull request by Lijuan-Z**

### CODE REVIEW

File: src/main/java/org/comp2522/ProjectRocketMan/Background.java [hunk 1]
```diff
@@ -26,7 +26,7 @@ public class Background extends Sprite {
   /**
    * Coins in the background.
    * */
-  ArrayList<Heart> coins;
+  ArrayList<Coin> coins;
```
Comment (immangat) [inline src/main/java/org/comp2522/ProjectRocketMan/Background.java:29]: This variable needs to be deleted.

**Review by immangat — CHANGES_REQUESTED** [review]

**Review by immangat — APPROVED** [review]
